# Generated by Django 4.2.3 on 2023-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Event", "0002_timetable_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeleId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("teleid", models.CharField(default="0000000", max_length=100)),
            ],
        ),
    ]
